name: Test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Add Rust (nightly)
      run: rustup toolchain install nightly
      
    - name: ethpm-spec
      run: git submodule sync --recursive && git submodule update --init --recursive
      
    - name: Build (std)
      run: cargo build --verbose

    - name: Build (wasm)
      run: cargo +nightly build --verbose --no-default-features --features no-std
      
    - name: Run tests
      run: cargo test --verbose
